#!/usr/bin/env bash
# Shared branch/PR management for automated skill improvement workflows.
# Both eval.yml and ai-changelog.yml source this script.
#
# Usage:
#   source .github/scripts/manage-improvement-pr.sh
#   setup_branch
#   # ... Claude makes changes and commits ...
#   push_and_pr "eval" "2026-03-22" "- fixed code-review regression"

set -euo pipefail

BRANCH="auto/skill-improvements"
PR_LABEL="automated-improvement"

setup_branch() {
  git config user.name "github-actions[bot]"
  git config user.email "github-actions[bot]@users.noreply.github.com"

  git fetch origin main

  if git ls-remote --exit-code --heads origin "$BRANCH" >/dev/null 2>&1; then
    git checkout "$BRANCH"
    git rebase origin/main || {
      echo "Rebase conflict — resetting branch to main"
      git rebase --abort
      git reset --hard origin/main
    }
  else
    git checkout -b "$BRANCH" origin/main
  fi
}

push_and_pr() {
  local source="$1"   # "eval" or "ai-changelog"
  local run_date="$2"  # YYYY-MM-DD
  local changes="$3"   # markdown bullet list of changes

  # Check if there are any changes to push
  if git diff --quiet origin/main..."$BRANCH" 2>/dev/null; then
    echo "No changes to push"
    return 0
  fi

  git push --force-with-lease origin "$BRANCH"

  # Check for existing PR
  local existing_pr
  existing_pr=$(gh pr list --head "$BRANCH" --state open --json number --jq '.[0].number // empty')

  local section_header="#### From ${source} (${run_date})"
  local new_section="${section_header}
${changes}"

  if [ -n "$existing_pr" ]; then
    # Append to existing PR body
    local current_body
    current_body=$(gh pr view "$existing_pr" --json body --jq '.body')
    local updated_body="${current_body}

${new_section}"
    gh pr edit "$existing_pr" --body "$updated_body"
    echo "Updated PR #${existing_pr}"
  else
    local body="## Automated Skill Improvements

### Changes in this PR

${new_section}

---
*Auto-generated by CI. Review before merging.*"

    gh pr create \
      --head "$BRANCH" \
      --base main \
      --title "chore(skills): automated skill improvements" \
      --body "$body" \
      --label "$PR_LABEL"
    echo "Created new PR"
  fi
}

check_staleness() {
  local max_age_days="${1:-30}"
  local existing_pr
  existing_pr=$(gh pr list --head "$BRANCH" --state open --json number,createdAt --jq '.[0] // empty')

  if [ -z "$existing_pr" ]; then
    return 0
  fi

  local pr_number
  pr_number=$(echo "$existing_pr" | jq -r '.number')
  local created_at
  created_at=$(echo "$existing_pr" | jq -r '.createdAt')
  local age_seconds
  age_seconds=$(( $(date +%s) - $(date -d "$created_at" +%s 2>/dev/null || date -j -f "%Y-%m-%dT%H:%M:%SZ" "$created_at" +%s) ))
  local age_days=$(( age_seconds / 86400 ))

  if [ "$age_days" -gt "$max_age_days" ]; then
    echo "PR #${pr_number} is ${age_days} days old (>${max_age_days}), closing as stale"
    gh pr close "$pr_number" --comment "Closing as stale (open for ${age_days} days without review). Improvements will be re-proposed in the next run."
    git push origin --delete "$BRANCH" 2>/dev/null || true
  fi
}
